
-- PART IV: PLAYER COMPARISON ANALYSIS
-- 1. View the players table
SELECT * FROM PLAYERS;
-- 2. Which players have the same birthday?
WITH BD AS (
	SELECT NAMEFIRST, CAST(CONCAT(BIRTHYEAR,'-',BIRTHMONTH,'-',BIRTHDAY) AS DATE) AS BIRTHDATE
	FROM PLAYERS)
		
SELECT BIRTHDATE,group_concat(NAMEFIRST SEPARATOR ', ') AS PLAYERS_NAMES
 FROM BD
WHERE YEAR(BIRTHDATE) BETWEEN 1980 AND 1990
GROUP BY BIRTHDATE
ORDER BY BIRTHDATE;

-- 3. Create a summary table that shows for each team, what percent of players bat right, left and both
SELECT S.TEAMID, 
	 ROUND(SUM(CASE WHEN P.BATS='R' THEN 1 ELSE 0 END) /  COUNT(S.PLAYERID)*100, 1)  AS BATS_RIGHT,    -- PIVOTING ( CONDITIONAL AGGREGATION)
     ROUND(SUM(CASE WHEN P.BATS='L' THEN 1 ELSE 0 END) / COUNT(S.PLAYERID)*100, 1)  AS BATS_LEFT,
     ROUND(SUM(CASE WHEN P.BATS='B' THEN 1 ELSE 0 END) /  COUNT(S.PLAYERID)*100, 1)  AS BATS_BOTH
FROM SALARIES S
LEFT JOIN PLAYERS P
ON S.PLAYERID = P.PLAYERID
GROUP BY S.TEAMID;


-- 4. How have average height and weight at debut game changed over the years, and what's the decade-over-decade difference?

WITH HW AS (SELECT ROUND(YEAR(DEBUT),-1) AS DECADE, AVG(HEIGHT) AS AVG_HEIGHT, AVG(WEIGHT) AS AVG_WEIGHT
FROM PLAYERS
GROUP BY DECADE)

SELECT DECADE,
	AVG_HEIGHT - LAG(AVG_HEIGHT) OVER(ORDER BY DECADE) AS HEIGHT_DIFF,
   AVG_WEIGHT - LAG(AVG_WEIGHT) OVER(ORDER BY DECADE) AS WEIGHT_DIFF
FROM HW
WHERE DECADE IS NOT NULL;









