
-- PART III: PLAYER CAREER ANALYSIS
-- 1. View the players table and find the number of players in the table

SELECT * FROM PLAYERS;
SELECT COUNT(DISTINCT PLAYERID) FROM PLAYERS;

-- 2. For each player, calculate their age at their first game, their last game, and their career length (all in years). Sort from longest career to shortest career.
WITH BD AS (SELECT NAMEGIVEN,DEBUT,FINALGAME,
	CAST(CONCAT(BIRTHYEAR,'-',BIRTHMONTH,'-',BIRTHDAY) AS DATE) AS BIRTHDATE
    FROM PLAYERS)
SELECT NAMEGIVEN,
			TIMESTAMPDIFF(YEAR,BIRTHDATE,DEBUT) AS STARTING_AGE,
			TIMESTAMPDIFF(YEAR,BIRTHDATE,FINALGAME) AS END_AGE,
			TIMESTAMPDIFF(YEAR,DEBUT,FINALGAME) AS CAREER_LENGHT
FROM BD
ORDER BY CAREER_LENGHT DESC;

-- 3. What team did each player play on for their starting and ending years?

SELECT NAMEGIVEN, S.YEARID AS STARTING_YEAR, S.TEAMID AS STARTING_TEAM, E.YEARID ENDING_YEAR, E.TEAMID AS ENDING_TEAM
FROM PLAYERS P INNER JOIN SALARIES S
						ON P.PLAYERID=S.PLAYERID
						AND YEAR(P.DEBUT)=S.YEARID
				INNER JOIN SALARIES E
						ON P.PLAYERID=E.PLAYERID
						AND YEAR(P.FINALGAME)=E.YEARID;

-- 4. How many players started and ended on the same team and also played for over a decade?


SELECT NAMEGIVEN, S.YEARID AS STARTING_YEAR, S.TEAMID AS STARTING_TEAM, E.YEARID ENDING_YEAR, E.TEAMID AS ENDING_TEAM
FROM PLAYERS P INNER JOIN SALARIES S
						ON P.PLAYERID=S.PLAYERID
						AND YEAR(P.DEBUT)=S.YEARID
				INNER JOIN SALARIES E
						ON P.PLAYERID=E.PLAYERID
						AND YEAR(P.FINALGAME)=E.YEARID
                        
WHERE S.TEAMID=E.TEAMID AND E.YEARID - S.YEARID >10 ;


