USE MAVEN_ADVANCED_SQL;

-- PART I: SCHOOL ANALYSIS

-- 1. VIEW THE SCHOOLS AND SCHOOL DETAILS TABLES
SELECT * FROM SCHOOLS;
SELECT * FROM SCHOOL_DETAILS;

-- 2. IN EACH DECADE, HOW MANY SCHOOLS WERE THERE THAT PRODUCED PLAYERS?
SELECT ROUND(YEARID, -1) AS DECADE, COUNT(DISTINCT SCHOOLID) AS NUM_SCHOOLS
FROM SCHOOLS
GROUP BY 1
ORDER BY 1;

-- 3. WHAT ARE THE NAMES OF THE TOP 5 SCHOOLS THAT PRODUCED THE MOST PLAYERS?
WITH SC AS (
    SELECT SCHOOLID, COUNT(DISTINCT PLAYERID) AS NUM_PLAYERS
    FROM SCHOOLS
    GROUP BY 1
)
SELECT S.NAME_FULL, SC.NUM_PLAYERS
FROM SC
LEFT JOIN SCHOOL_DETAILS S ON SC.SCHOOLID = S.SCHOOLID
ORDER BY NUM_PLAYERS DESC
LIMIT 5;

-- 4. FOR EACH DECADE, WHAT WERE THE NAMES OF THE TOP 3 SCHOOLS THAT PRODUCED THE MOST PLAYERS?
WITH SC AS (
    SELECT ROUND(YEARID, -1) AS DECADE, SCHOOLID, COUNT(DISTINCT PLAYERID) AS NUM_PLAYERS
    FROM SCHOOLS
    GROUP BY 1, 2
),
SCD2 AS (
    SELECT D.DECADE, SD.NAME_FULL AS SCHOOL_NAME, D.NUM_PLAYERS,
           ROW_NUMBER() OVER (PARTITION BY D.DECADE ORDER BY D.NUM_PLAYERS DESC) AS TOP
    FROM SC D
    LEFT JOIN SCHOOL_DETAILS SD ON D.SCHOOLID = SD.SCHOOLID
)
SELECT DECADE, SCHOOL_NAME, NUM_PLAYERS
FROM SCD2
WHERE TOP IN (1, 2, 3)
ORDER BY DECADE DESC, TOP;
