
-- PART II: SALARY ANALYSIS
USE maven_advanced_sql;
-- 1. View the salaries table
SELECT * FROM SALARIES LIMIT 100;

-- 2. Return the top 20% of teams in terms of average annual spending

WITH TS AS (SELECT YEARID,TEAMID,SUM(SALARY) AS TOTAL_SPEND
FROM SALARIES
GROUP BY 1,2
ORDER BY 1,2),

SP AS (SELECT TEAMID,AVG(TOTAL_SPEND)  AS  AVG_SPEND,
	NTILE(5) OVER(ORDER BY AVG(TOTAL_SPEND) DESC)  AS SPEND_PCT 
FROM TS
GROUP BY TEAMID)

SELECT TEAMID, ROUND(AVG_SPEND/1000000,1) AS AVG_SPEND_MILLIONS
FROM SP
WHERE SPEND_PCT=1
;

-- 3. For each team, show the cumulative sum of spending over the years

WITH TS AS (SELECT TEAMID,YEARID,sum(SALARY) AS TOTAL_SPEND
FROM SALARIES
GROUP BY 1,2
ORDER BY 1,2)

SELECT TEAMID,YEARID,
	ROUND(SUM(TOTAL_SPEND) OVER(PARTITION BY TEAMID ORDER BY YEARID)/1000000,1) AS CUMULATIVE_SUM_MILLIONS
FROM TS;

-- 4. Return the first year that each team's cumulative spending surpassed 1 billion
WITH TS AS (SELECT TEAMID,YEARID,sum(SALARY) AS TOTAL_SPEND
FROM SALARIES
GROUP BY 1,2
ORDER BY 1,2),

CS AS (SELECT TEAMID,YEARID,
	SUM(TOTAL_SPEND) OVER(PARTITION BY TEAMID ORDER BY YEARID) AS CUMULATIVE_SUM
FROM TS),

RN AS (SELECT TEAMID,YEARID,CUMULATIVE_SUM,
	ROW_NUMBER() OVER(PARTITION BY TEAMID ORDER BY CUMULATIVE_SUM) AS RN
FROM CS
WHERE CUMULATIVE_SUM>1000000000)

SELECT TEAMID,YEARID,ROUND(CUMULATIVE_SUM/1000000000,2) AS
CUMULATIVE_SUM_BILLIONS
FROM RN
WHERE RN=1;

